import { ProductManifest } from "@prosis/sdk";

export const SEATBOOKING_MANIFEST: ProductManifest = {
  id: "seatbooking",
  name: "Seatbooking",
  slug: "seatbooking",
  description: "Enterprise hospitality & restaurant reservation operations SaaS",
  icon: "UtensilsCrossed",
  version: "2.4.0",
  status: "active",
  capabilities: [
    {
      id: "restaurants",
      name: "Restaurant Operations",
      description: "Track restaurant venues, capacity, floor plans, and operating pacing.",
      version: "2.0",
      operations: ["getRestaurants", "getRestaurant"],
    },
    {
      id: "reservations",
      name: "Reservations Management",
      description: "Query, allocate, reschedule, and cancel table bookings in real-time.",
      version: "2.0",
      operations: [
        "getReservations",
        "getReservation",
        "createReservation",
        "updateReservation",
        "cancelReservation",
      ],
    },
    {
      id: "customers",
      name: "Customer & VIP CRM",
      description: "Guest dietary preferences, VIP notes, party histories, and profile lookups.",
      version: "1.8",
      operations: ["getCustomer"],
    },
    {
      id: "analytics",
      name: "Reservation & Venue Analytics",
      description: "Booking trajectories, cancellation velocities, occupancy forecasting, and performance metrics.",
      version: "2.1",
      operations: [
        "getRestaurantAnalytics",
        "getReservationAnalytics",
        "getDailyBriefing",
        "getDecliningRestaurants",
      ],
    },
  ],
  tools: [
    "seatbooking_getRestaurants",
    "seatbooking_getRestaurant",
    "seatbooking_getReservations",
    "seatbooking_getReservation",
    "seatbooking_getCustomer",
    "seatbooking_getRestaurantAnalytics",
    "seatbooking_getReservationAnalytics",
    "seatbooking_createReservation",
    "seatbooking_updateReservation",
    "seatbooking_cancelReservation",
    "seatbooking_getDailyBriefing",
    "seatbooking_getDecliningRestaurants",
    "seatbooking_prepareCampaignDrafts",
    "seatbooking_sendEmail",
  ],
  navigation: [
    { label: "Floor & Bookings", path: "/seatbooking/reservations", icon: "Calendar" },
    { label: "Restaurant Venues", path: "/seatbooking/restaurants", icon: "UtensilsCrossed" },
    { label: "Guest CRM", path: "/seatbooking/customers", icon: "Users" },
    { label: "Pacing Analytics", path: "/seatbooking/analytics", icon: "BarChart3" },
  ],
  workspace: {
    id: "workspace_seatbooking",
    title: "Seatbooking Operations Workspace",
    slug: "seatbooking",
    route: "/seatbooking",
    layout: "split",
    quickActions: [
      { label: "Book Table", action: "create_reservation", icon: "Plus" },
      { label: "Daily Briefing", action: "view_briefing", icon: "Sparkles" },
    ],
  },
  apiConfig: {
    baseUrl: "https://api.seatbooking.internal/v2",
    apiVersion: "2026-03",
    authStrategy: "internal_service",
    timeoutMs: 4000,
  },
  permissions: [
    "seatbooking.read",
    "seatbooking.reservations.write",
    "seatbooking.communications.send",
    "seatbooking.admin",
  ],
  enabled: true,
};
